version: "3"

services:
  web:
    container_name: web
    build:
      args:
        - PORT=3000
        - PROJECT=web
      context: .
      dockerfile: ./Dockerfile.web
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  api:
    container_name: api
    build:
      args:
        - PORT=3001
        - PROJECT=api
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
